---
- hosts: pvenodes
  become: true
  tasks:
    - name:  Update Repo Cache
      apt:
        update_cache: yes
        cache_valid_time:  3600

    - name:  Install ProxMoxer
      apt:
        name:
        - python3-proxmoxer
        state: latest