#Create download folder
- name: Create download folder
  file:
    path: '{{image_path}}'
    state: directory

- name: Download cloud-init images
  get_url:
    url: '{{item.image.url}}'
    dest: '{{image_path}}{{item.cloud_init_file}}'
    checksum: 'item.state == "present"'
  loop: '{{os.images}}'
  when: 'item.state == "present"'

- name: Delete unused cloud-init images
  file:
    path: '{{image_path}}{{item.cloud_init_file}}'
    state: absent
  loop: '{{os_images}}'
  when: 'item.state == "absent"'